// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: internal/model/coordinator.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_REQUEST_TYPE_UNSPECIFIED RequestType = 0
	RequestType_REQUEST_TYPE_REGISTER    RequestType = 1
	RequestType_REQUEST_TYPE_UNREGISTER  RequestType = 2
	RequestType_REQUEST_TYPE_ERROR       RequestType = 3
	RequestType_REQUEST_TYPE_PROMPT      RequestType = 4
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "REQUEST_TYPE_UNSPECIFIED",
		1: "REQUEST_TYPE_REGISTER",
		2: "REQUEST_TYPE_UNREGISTER",
		3: "REQUEST_TYPE_ERROR",
		4: "REQUEST_TYPE_PROMPT",
	}
	RequestType_value = map[string]int32{
		"REQUEST_TYPE_UNSPECIFIED": 0,
		"REQUEST_TYPE_REGISTER":    1,
		"REQUEST_TYPE_UNREGISTER":  2,
		"REQUEST_TYPE_ERROR":       3,
		"REQUEST_TYPE_PROMPT":      4,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_model_coordinator_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_internal_model_coordinator_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_internal_model_coordinator_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        *string                `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_model_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_model_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        *string                `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_internal_model_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_model_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *UnregisterRequest) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        *string                `protobuf:"bytes,1,opt,name=prompt" json:"prompt,omitempty"`
	PromptHistory []string               `protobuf:"bytes,2,rep,name=prompt_history,json=promptHistory" json:"prompt_history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_internal_model_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_internal_model_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *PromptRequest) GetPrompt() string {
	if x != nil && x.Prompt != nil {
		return *x.Prompt
	}
	return ""
}

func (x *PromptRequest) GetPromptHistory() []string {
	if x != nil {
		return x.PromptHistory
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        *string                `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_internal_model_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_model_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        *string                `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_internal_model_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_model_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterResponse) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

func (x *UnregisterResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type PromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *string                `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	PromptHistory []string               `protobuf:"bytes,2,rep,name=prompt_history,json=promptHistory" json:"prompt_history,omitempty"`
	IsComplete    *bool                  `protobuf:"varint,3,opt,name=is_complete,json=isComplete" json:"is_complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptResponse) Reset() {
	*x = PromptResponse{}
	mi := &file_internal_model_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptResponse) ProtoMessage() {}

func (x *PromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptResponse.ProtoReflect.Descriptor instead.
func (*PromptResponse) Descriptor() ([]byte, []int) {
	return file_internal_model_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *PromptResponse) GetResponse() string {
	if x != nil && x.Response != nil {
		return *x.Response
	}
	return ""
}

func (x *PromptResponse) GetPromptHistory() []string {
	if x != nil {
		return x.PromptHistory
	}
	return nil
}

func (x *PromptResponse) GetIsComplete() bool {
	if x != nil && x.IsComplete != nil {
		return *x.IsComplete
	}
	return false
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_internal_model_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_internal_model_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type ConnectRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      *RequestType           `protobuf:"varint,1,opt,name=type,enum=routeguide.RequestType" json:"type,omitempty"`
	Timestamp *int64                 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*ConnectRequest_Register
	//	*ConnectRequest_Unregister
	//	*ConnectRequest_Prompt
	Request       isConnectRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_internal_model_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_model_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectRequest) GetType() RequestType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return RequestType_REQUEST_TYPE_UNSPECIFIED
}

func (x *ConnectRequest) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *ConnectRequest) GetRequest() isConnectRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ConnectRequest) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Request.(*ConnectRequest_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ConnectRequest) GetUnregister() *UnregisterRequest {
	if x != nil {
		if x, ok := x.Request.(*ConnectRequest_Unregister); ok {
			return x.Unregister
		}
	}
	return nil
}

func (x *ConnectRequest) GetPrompt() *PromptRequest {
	if x != nil {
		if x, ok := x.Request.(*ConnectRequest_Prompt); ok {
			return x.Prompt
		}
	}
	return nil
}

type isConnectRequest_Request interface {
	isConnectRequest_Request()
}

type ConnectRequest_Register struct {
	Register *RegisterRequest `protobuf:"bytes,3,opt,name=register,oneof"`
}

type ConnectRequest_Unregister struct {
	Unregister *UnregisterRequest `protobuf:"bytes,4,opt,name=unregister,oneof"`
}

type ConnectRequest_Prompt struct {
	Prompt *PromptRequest `protobuf:"bytes,5,opt,name=prompt,oneof"`
}

func (*ConnectRequest_Register) isConnectRequest_Request() {}

func (*ConnectRequest_Unregister) isConnectRequest_Request() {}

func (*ConnectRequest_Prompt) isConnectRequest_Request() {}

type ConnectResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      *RequestType           `protobuf:"varint,1,opt,name=type,enum=routeguide.RequestType" json:"type,omitempty"`
	Timestamp *int64                 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*ConnectResponse_Register
	//	*ConnectResponse_Unregister
	//	*ConnectResponse_Prompt
	//	*ConnectResponse_Error
	Response      isConnectResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_internal_model_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_model_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectResponse) GetType() RequestType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return RequestType_REQUEST_TYPE_UNSPECIFIED
}

func (x *ConnectResponse) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *ConnectResponse) GetResponse() isConnectResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ConnectResponse) GetRegister() *RegisterResponse {
	if x != nil {
		if x, ok := x.Response.(*ConnectResponse_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ConnectResponse) GetUnregister() *UnregisterResponse {
	if x != nil {
		if x, ok := x.Response.(*ConnectResponse_Unregister); ok {
			return x.Unregister
		}
	}
	return nil
}

func (x *ConnectResponse) GetPrompt() *PromptResponse {
	if x != nil {
		if x, ok := x.Response.(*ConnectResponse_Prompt); ok {
			return x.Prompt
		}
	}
	return nil
}

func (x *ConnectResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Response.(*ConnectResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isConnectResponse_Response interface {
	isConnectResponse_Response()
}

type ConnectResponse_Register struct {
	Register *RegisterResponse `protobuf:"bytes,3,opt,name=register,oneof"`
}

type ConnectResponse_Unregister struct {
	Unregister *UnregisterResponse `protobuf:"bytes,4,opt,name=unregister,oneof"`
}

type ConnectResponse_Prompt struct {
	Prompt *PromptResponse `protobuf:"bytes,5,opt,name=prompt,oneof"`
}

type ConnectResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,6,opt,name=error,oneof"`
}

func (*ConnectResponse_Register) isConnectResponse_Response() {}

func (*ConnectResponse_Unregister) isConnectResponse_Response() {}

func (*ConnectResponse_Prompt) isConnectResponse_Response() {}

func (*ConnectResponse_Error) isConnectResponse_Response() {}

var File_internal_model_coordinator_proto protoreflect.FileDescriptor

const file_internal_model_coordinator_proto_rawDesc = "" +
	"\n" +
	" internal/model/coordinator.proto\x12\n" +
	"routeguide\"*\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\",\n" +
	"\x11UnregisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"N\n" +
	"\rPromptRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12%\n" +
	"\x0eprompt_history\x18\x02 \x03(\tR\rpromptHistory\"E\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x12UnregisterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"t\n" +
	"\x0ePromptResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12%\n" +
	"\x0eprompt_history\x18\x02 \x03(\tR\rpromptHistory\x12\x1f\n" +
	"\vis_complete\x18\x03 \x01(\bR\n" +
	"isComplete\")\n" +
	"\rErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x97\x02\n" +
	"\x0eConnectRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.routeguide.RequestTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x129\n" +
	"\bregister\x18\x03 \x01(\v2\x1b.routeguide.RegisterRequestH\x00R\bregister\x12?\n" +
	"\n" +
	"unregister\x18\x04 \x01(\v2\x1d.routeguide.UnregisterRequestH\x00R\n" +
	"unregister\x123\n" +
	"\x06prompt\x18\x05 \x01(\v2\x19.routeguide.PromptRequestH\x00R\x06promptB\t\n" +
	"\arequest\"\xcf\x02\n" +
	"\x0fConnectResponse\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.routeguide.RequestTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12:\n" +
	"\bregister\x18\x03 \x01(\v2\x1c.routeguide.RegisterResponseH\x00R\bregister\x12@\n" +
	"\n" +
	"unregister\x18\x04 \x01(\v2\x1e.routeguide.UnregisterResponseH\x00R\n" +
	"unregister\x124\n" +
	"\x06prompt\x18\x05 \x01(\v2\x1a.routeguide.PromptResponseH\x00R\x06prompt\x121\n" +
	"\x05error\x18\x06 \x01(\v2\x19.routeguide.ErrorResponseH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse*\x94\x01\n" +
	"\vRequestType\x12\x1c\n" +
	"\x18REQUEST_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REQUEST_TYPE_REGISTER\x10\x01\x12\x1b\n" +
	"\x17REQUEST_TYPE_UNREGISTER\x10\x02\x12\x16\n" +
	"\x12REQUEST_TYPE_ERROR\x10\x03\x12\x17\n" +
	"\x13REQUEST_TYPE_PROMPT\x10\x042U\n" +
	"\vCoordinator\x12F\n" +
	"\aConnect\x12\x1a.routeguide.ConnectRequest\x1a\x1b.routeguide.ConnectResponse(\x010\x01B3Z1github.com/khosbilegt/llama-drover/internal/modelb\beditionsp\xe8\a"

var (
	file_internal_model_coordinator_proto_rawDescOnce sync.Once
	file_internal_model_coordinator_proto_rawDescData []byte
)

func file_internal_model_coordinator_proto_rawDescGZIP() []byte {
	file_internal_model_coordinator_proto_rawDescOnce.Do(func() {
		file_internal_model_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_model_coordinator_proto_rawDesc), len(file_internal_model_coordinator_proto_rawDesc)))
	})
	return file_internal_model_coordinator_proto_rawDescData
}

var file_internal_model_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_model_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_model_coordinator_proto_goTypes = []any{
	(RequestType)(0),           // 0: routeguide.RequestType
	(*RegisterRequest)(nil),    // 1: routeguide.RegisterRequest
	(*UnregisterRequest)(nil),  // 2: routeguide.UnregisterRequest
	(*PromptRequest)(nil),      // 3: routeguide.PromptRequest
	(*RegisterResponse)(nil),   // 4: routeguide.RegisterResponse
	(*UnregisterResponse)(nil), // 5: routeguide.UnregisterResponse
	(*PromptResponse)(nil),     // 6: routeguide.PromptResponse
	(*ErrorResponse)(nil),      // 7: routeguide.ErrorResponse
	(*ConnectRequest)(nil),     // 8: routeguide.ConnectRequest
	(*ConnectResponse)(nil),    // 9: routeguide.ConnectResponse
}
var file_internal_model_coordinator_proto_depIdxs = []int32{
	0,  // 0: routeguide.ConnectRequest.type:type_name -> routeguide.RequestType
	1,  // 1: routeguide.ConnectRequest.register:type_name -> routeguide.RegisterRequest
	2,  // 2: routeguide.ConnectRequest.unregister:type_name -> routeguide.UnregisterRequest
	3,  // 3: routeguide.ConnectRequest.prompt:type_name -> routeguide.PromptRequest
	0,  // 4: routeguide.ConnectResponse.type:type_name -> routeguide.RequestType
	4,  // 5: routeguide.ConnectResponse.register:type_name -> routeguide.RegisterResponse
	5,  // 6: routeguide.ConnectResponse.unregister:type_name -> routeguide.UnregisterResponse
	6,  // 7: routeguide.ConnectResponse.prompt:type_name -> routeguide.PromptResponse
	7,  // 8: routeguide.ConnectResponse.error:type_name -> routeguide.ErrorResponse
	8,  // 9: routeguide.Coordinator.Connect:input_type -> routeguide.ConnectRequest
	9,  // 10: routeguide.Coordinator.Connect:output_type -> routeguide.ConnectResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_internal_model_coordinator_proto_init() }
func file_internal_model_coordinator_proto_init() {
	if File_internal_model_coordinator_proto != nil {
		return
	}
	file_internal_model_coordinator_proto_msgTypes[7].OneofWrappers = []any{
		(*ConnectRequest_Register)(nil),
		(*ConnectRequest_Unregister)(nil),
		(*ConnectRequest_Prompt)(nil),
	}
	file_internal_model_coordinator_proto_msgTypes[8].OneofWrappers = []any{
		(*ConnectResponse_Register)(nil),
		(*ConnectResponse_Unregister)(nil),
		(*ConnectResponse_Prompt)(nil),
		(*ConnectResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_model_coordinator_proto_rawDesc), len(file_internal_model_coordinator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_model_coordinator_proto_goTypes,
		DependencyIndexes: file_internal_model_coordinator_proto_depIdxs,
		EnumInfos:         file_internal_model_coordinator_proto_enumTypes,
		MessageInfos:      file_internal_model_coordinator_proto_msgTypes,
	}.Build()
	File_internal_model_coordinator_proto = out.File
	file_internal_model_coordinator_proto_goTypes = nil
	file_internal_model_coordinator_proto_depIdxs = nil
}
